#ifndef IC_ERR_H_
#define IC_ERR_H_

enum {
    IC_ERR_SRV_BADADDR = 1,
    IC_ERR_SRV_CONNECT,
    IC_ERR_SRV_SOCKET,
    IC_ERR_QUERY_NULL,
    IC_ERR_ENOMEM,
    IC_ERR_SRV_NONBLOCK,
    IC_ERR_SRV_TIMEOUT,
    IC_ERR_SRV_UNREACH,
    IC_ERR_SOCKET_OPTS,
    IC_ERR_SOCKET_NO_EVENTS,
    IC_ERR_SELECT,
    IC_ERR_SEND_PARTED,
    IC_ERR_SEND,
    IC_ERR_NON_ICAP,
    IC_ERR_HEADER_END,
    IC_ERR_ICAP_BAD_REQUEST,
    IC_ERR_BAD_HEADER,
    IC_ERR_NULL_POINTER_INT,
    IC_ERR_INVAL_LEN_INT,
    IC_ERR_INT_OVERFLOW_INT,
    IC_ERR_NULL_POINTER,
    IC_ERR_INT_OVERFLOW,
    IC_ERR_BAD_INT,
    IC_ERR_STATUS_NOT_FOUND,
    IC_ERR_BAD_REQUEST,
    IC_ERR_METHODS_NOT_FOUND,
    IC_ERR_CONN_CLOSED,
    IC_ERR_REQ_TIMEOUT,
    IC_ERR_COUNT
};

#endif
